---
title: "Written_Lesson01"
author: "Richard Griffiths"
date: "19 July 2016"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set your working directory ready
```
setwd("E:/Documents/Projects/ShinyTutorial")
```

Install shiny package
```
install.packages("shiny") ##installs shiny
```

Add shiny package
```
library(shiny) ##adds shiny package
```

Run built in example 01
```
runExample("01_hello") ##11 examples available
```

User defined apps comprise of two files
ui.r and server.R
Save these in a folder (e.g. App-1) and can then call it.

```
runApp("Written_Lesson01/App-1")
```

shows the code alongside app
```
runApp("Written_Lesson01/App-1", display.mode = "showcase") 
```

below are all the examples as they are default to showcase
you can see all the code with them when run.
So you can steal them as starting points :).

a histogram
```
runExample("01_hello") 
```
tables and data frames
```
runExample("02_text") 
```
a reactive expression - outputs change as soon as input does
```
runExample("03_reactivity") 
```
global variables
```
runExample("04_mpg") 
```
slider bars - shows animating acorss slider bars too
```
runExample("05_sliders") 
```
tabbed panels - summary plot and table on tabs
```
runExample("06_tabsets")
```
help text and submit buttons
```
runExample("07_widgets") 
```
Shiny app built from HTML
```
runExample("08_html") 
```
file upload wizard
```
runExample("09_upload") 
```
file download wizard - allows to download a dataset in csv erc
```
runExample("10_download") 
```
An automated timer - Shows a ticking clock so responsive to the time
```
runExample("11_timer") 
```



